services:

  redis:
    image: redis:7
    networks:
      - dc_network
    command:
      - redis-server
      - --bind
      - "0.0.0.0"
      - --requirepass
      - "${REDIS_PASSWORD}"             # 環境変数でパスワードを設定:contentReference[oaicite:2]{index=2}
      - --masterauth
      - "${REDIS_PASSWORD}"             # レプリケーション用パスワード:contentReference[oaicite:3]{index=3}
      - --masteruser
      - "${REDIS_USER}"                 # レプリケーション用ユーザー:contentReference[oaicite:4]{index=4}
      - --appendonly
      - "no"
      - --protected-mode
      - "yes"


  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dc_network
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    ports:
      - "10000:8080"
    env_file:
      - .env
    stdin_open: true

  db:
    image: postgres:14.13-bookworm
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - dc_network
    env_file:
      - .env
      
volumes:
  db_data:

networks:
  dc_network:
    external: true  # 既存のネットワークを使用